# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        run: |
         echo deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/| sudo tee -a /etc/apt/sources.list 
         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
         sudo apt update
         sudo apt install r-base r-base-core r-recommended r-base-dev libcurl4-openssl-dev libssl-dev libxml2-dev
         Rscript -e 'install.packages("devtools")'
      - name: Test
        run: make test
