name: Test_LNCDR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        runs:
          using: 'docker'
          image: 'Dockerfile'
          entrypoint: ["Rscript", "-e", "setwd('/lncdr/tests/'); source('testthat.R')"]

