name: Test_LNCDR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        run: |
         echo deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/| sudo tee -a /etc/apt/sources.list 
         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
         sudo apt update
         sudo apt install r-base r-base-core r-recommended r-base-dev libcurl4-openssl-dev libssl-dev libxml2-dev
         export R_LIBS_USER=~/R_libs/ 
         mkdir -p $R_LIBS_USER
         Rscript -e 'install.packages("devtools")'
      - name: Test
        run: |
          export R_LIBS_USER=~/R_libs/ 
          make test
